const assert=require('assert'),fs=require('fs'),vm=require('vm');
const src=fs.readFileSync('app.js','utf8');
function el(tag='div'){return {tagName:tag.toUpperCase(),children:[],dataset:{},textContent:'',innerHTML:'',className:'',hidden:false,disabled:false,attributes:{},classList:{hidden:false,add(c){this[c]=true},remove(c){this[c]=false},toggle(c,v){this[c]=v===undefined?!this[c]:v}},setAttribute(k,v){this.attributes[k]=v},appendChild(x){this.children.push(x);return x},append(...x){this.children.push(...x)},replaceChildren(...x){this.children=x},addEventListener(){}}}
const ids=['portfolio-positions','position-list-status','overview-heading','overview-position','overview-balance','overview-authority','overview-evidence','overview-protection','portfolio-protocol-status','portfolio-coverage','portfolio-safeguards','safeguards-summary','position-card','position-row','position-list','no-position','position-name','position-protocol','position-network','position-token','position-status','amount','position-amount','position-total-shares','position-staked-shares','position-unstaked-shares','position-total-shares-readable','position-staked-shares-readable','position-unstaked-shares-readable','position-tokens-per-share','share-detail','position-vault','position-program','position-activity','activity-status','position-protection'];
const els=Object.fromEntries(ids.map(id=>[id,el()]));els['position-tabs']=el();
const document={createElement:tag=>el(tag),querySelector(s){if(s==='.position-tabs')return els['position-tabs'];return s[0]==='#'?els[s.slice(1)]:null},querySelectorAll(s){if(s.includes('.position-row'))return els['portfolio-positions'].children;return []}};
const ctx={document,$:s=>document.querySelector(s),setText:(s,v)=>{const x=document.querySelector(s);if(x)x.textContent=String(v)},format:v=>String(v),authorityAssessment(){return {label:'x'}},vaultRoleCoverage(){return {missing:[],total:0}},observedCopy(){return 'observed'},networkLabel(){return 'Mainnet'},positionSearchPending(){return false},positionEmptyCopy(){return 'empty'},clearInterval(){},setInterval(){return 1},pendingTimer:null,protectionStatus:null,renderAuthority(){},toast(){},console,CURRENT_NETWORK:'mainnet-beta'};
const overview=src.slice(src.indexOf('function renderOverview'),src.indexOf('function updateProtectionCopy'));
const portfolioSource=src.slice(src.indexOf('function renderPortfolio'),src.indexOf('function renderAuthority'));
vm.runInNewContext(overview+portfolioSource+';this.renderPortfolio=renderPortfolio;this.selectPortfolioPosition=selectPortfolioPosition;this.renderPortfolioSafeguards=renderPortfolioSafeguards',ctx);
const portfolio={positions:[{targetId:'a',protocol:'Kamino',display:{name:'<img src=x>',amount:'10'},safeguards:[{targetId:'a',ruleId:'r1',result:'pass',reason:'receipt pending'}]},{targetId:'b',protocol:'Generic',display:{name:'Second',amount:'20'},safeguards:[]}],safeguards:[{targetId:'a',ruleId:'r1',result:'pass',reason:'receipt pending'}],protocolStatuses:[],coverage:{state:'partial'}};
ctx.portfolioState=portfolio;ctx.renderPortfolio(portfolio);
assert.strictEqual(els['portfolio-positions'].children.length,2);assert.strictEqual(els['overview-position'].textContent,'2');
ctx.selectPortfolioPosition('b');
assert.strictEqual(els['portfolio-positions'].children.length,2);assert.strictEqual(els['overview-position'].textContent,'2','Overview count remains canonical after selecting a position');
assert.strictEqual(els['portfolio-positions'].children[1].attributes['aria-selected'],'true');
assert.strictEqual(els['portfolio-safeguards'].children.length,2,'all discovered vaults remain visible');
assert.strictEqual(els['portfolio-safeguards'].children[0].textContent,'<img src=x> (a): r1: unknown — receipt pending');
assert.strictEqual(els['portfolio-safeguards'].children[1].textContent,'Second (b): No safeguards reported');
assert.strictEqual(els['safeguards-summary'].textContent,'Safeguard evidence');
assert.strictEqual(els['portfolio-coverage'].textContent,'Coverage partial: unknown/unknown satisfied');
console.log('portfolio runtime passed');
