const assert=require('assert'),fs=require('fs');
const app=fs.readFileSync('app.js','utf8'),css=fs.readFileSync('styles.css','utf8'),html=fs.readFileSync('app.html','utf8');
assert.match(css,/#network-context-label/,'network control has explicit production styling');
assert.match(css,/\.modal\{[^}]*position:fixed/,'modal is viewport anchored');
assert.match(css,/\.modal\{[^}]*justify-content:center/,'modal is horizontally centered');
assert.match(css,/\.modal\{[^}]*align-items:center/,'modal is vertically centered');
assert.match(css,/[^\n]*#toast[^}]*position:fixed/,'toast is viewport anchored');
assert.match(css,/[^\n]*#toast[^}]*left:50%/,'toast is horizontally centered');
assert.match(css,/[^\n]*#toast[^}]*bottom:24px/,'toast is bottom anchored');
assert.match(css,/[^\n]*#toast[^}]*transform:translateX\(-50%\)/,'toast uses bottom-center transform');
assert.doesNotMatch(css,/[^\n]*#toast[^}]*top:50%/,'toast is not vertically centered');
assert.doesNotMatch(css,/[^\n]*#toast[^}]*transform:translate\(-50%,-50%\)/,'toast does not use viewport-center transform');
assert.match(app,/NETWORK_RECONNECT_KEY/,'network switch records fresh-auth reconnect intent');
assert.match(app,/connectWallet\(reconnect\.source(?:,\{protectedStartup:true\})?\)/,'reload consumes reconnect intent with protected startup semantics');
assert.match(app,/sessionStorage\.removeItem\(NETWORK_RECONNECT_KEY\)/,'reconnect intent is one-shot');
assert.match(app,/clearNetworkScopedState\(\)/,'switch clears scoped state');
assert.match(app,/previous\.disconnect/,'switch has provider disconnect barrier');
console.log('network switch UI regression passed');
