const assert=require('assert'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync('app.js','utf8');
const MAIN='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d';
const key='StaleContinuationWallet111111111111111111111111111111';
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject}}
function store(seed={}){const data=new Map(Object.entries(seed));return{getItem(k){return data.has(k)?data.get(k):null},setItem(k,v){data.set(k,String(v))},removeItem(k){data.delete(k)}}}
function node(){return{hidden:true,classList:{add(){},remove(){},toggle(){}},style:{setProperty(){}},dataset:{},value:'',disabled:false,textContent:'',innerHTML:'',onclick:null,onchange:null,onkeydown:null,addEventListener(){},setAttribute(){},replaceChildren(){},appendChild(){},closest(){return this},getBoundingClientRect(){return{left:0,top:0,width:1,height:1}}}}
function harness({portfolioStatus=200,portfolioBody={positions:[],safeguards:[],protocolStatuses:[],coverage:{}},protectionResponse=null,portfolioResponse=null}={}){
 const sessionStorage=store({kelvara_network_context:'mainnet-beta',kelvara_app_session:JSON.stringify({wallet:key,source:'phantom',token:'trusted-token',network:'mainnet-beta',genesisHash:MAIN})}),localStorage=store(),nodes=new Map(),events={},redirects=[],calls=[];
 const pendingProtection=protectionResponse||deferred(),pendingChallenge=deferred();
 const provider={isConnected:true,publicKey:{toString:()=>key},on(name,handler){events[name]=handler},emit(name,value){events[name]?.(value)},async connect(){return{publicKey:this.publicKey}},async signMessage(){return{signature:Uint8Array.of(1)}},async disconnect(){events.disconnect?.()}};
 const document={body:node(),querySelector(selector){if(selector.startsWith('#')){if(!nodes.has(selector.slice(1)))nodes.set(selector.slice(1),node());return nodes.get(selector.slice(1))}return node()},querySelectorAll(){return[]},createElement:node,addEventListener(){}};
 const location={hostname:'localhost',hash:'',replace(url){redirects.push(url)}};
 const fetch=async(url,options)=>{calls.push([url,options||{}]);if(url==='/healthz')return{ok:true,status:200,text:async()=>JSON.stringify({ok:true})};if(url.includes('/api/portfolio/'))return portfolioResponse?.promise||{ok:portfolioStatus>=200&&portfolioStatus<300,status:portfolioStatus,text:async()=>JSON.stringify(portfolioBody)};if(url.includes('/api/protection/status'))return pendingProtection.promise;if(url.endsWith('/api/auth/challenge'))return pendingChallenge.promise;if(url.endsWith('/api/auth/verify'))return{ok:true,status:200,text:async()=>JSON.stringify({token:'verified-token',network:'mainnet-beta',genesisHash:MAIN})};return{ok:true,status:200,text:async()=>JSON.stringify({})}};
 const context={document,window:{addEventListener(){},scrollTo(){},phantom:{solana:provider}},location,localStorage,sessionStorage,normalizeNetwork:value=>value==='mainnet-beta'||value==='devnet'?value:null,validateDevnetPortfolio:value=>value,projectDevnetView:value=>({networkLabel:'Devnet',positionLabel:'0 positions',emptyLabel:'No Devnet positions'}),devnetRequest:()=>({path:'/api/portfolio/'+key,headers:{authorization:'Bearer trusted-token'}}),fetch,setTimeout,clearTimeout,setInterval:()=>1,clearInterval,Promise,URLSearchParams,Intl,DOMParser:class{},TextEncoder,atob:()=>'',btoa:()=>'',matchMedia:()=>({matches:false}),console,animalIdenticonSvg:()=>''};
 const code=source.replace(/^import[^\n]*\n/gm,'').replace(/\ninit\(\);\s*$/,'')+`\nglobalThis.test={init,loadProtection,inspect,connectWallet,bindWalletEvents,setAuthenticated(address,source,p){walletAddress=address;walletSource=source;activeProvider=p;protectionToken='trusted-token';verifiedGenesisHash='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d';bindWalletEvents(p)},state(){return{protectionTitle:document.querySelector('#protection-title').textContent,connectionTitle:document.querySelector('#wallet-progress-title').textContent,overviewHeading:document.querySelector('#overview-heading').textContent,workspaceHidden:document.querySelector('#connected-workspace').hidden}}};`;
 vm.runInNewContext(code,context,{filename:'app.js'});
 return{context,provider,redirects,calls,pendingProtection,pendingChallenge,nodes};
}
(async()=>{
 const protection=harness();protection.context.test.setAuthenticated(key,'phantom',protection.provider);const protectionRun=protection.context.test.loadProtection();protection.provider.emit('disconnect');protection.pendingProtection.resolve({ok:true,status:200,text:async()=>JSON.stringify({armed:false,network:'mainnet-beta',genesisHash:MAIN})});await protectionRun;assert.notStrictEqual(protection.context.test.state().protectionTitle,'Protection status unavailable','stale protection response must not render after invalidation');assert.deepStrictEqual(protection.redirects,['/?wallet_error=session'],'protection invalidation redirects once');
 const init=harness({portfolioStatus:401,portfolioBody:{error:'expired'},protectionResponse:deferred()});const initRun=init.context.test.init();await new Promise(resolve=>setImmediate(resolve));init.pendingProtection.resolve({ok:true,status:200,text:async()=>JSON.stringify({armed:false,network:'mainnet-beta',genesisHash:MAIN})});await initRun;assert.notStrictEqual(init.context.test.state().protectionTitle,'Not armed','init must stop before rendering protection after invalidation');assert.deepStrictEqual(init.redirects,['/?wallet_error=session'],'init invalidation redirects once');
 const inspect=harness({portfolioStatus:401,portfolioBody:{error:'expired'}});inspect.context.test.setAuthenticated(key,'phantom',inspect.provider);await assert.rejects(()=>inspect.context.test.inspect(),/expired|Portfolio unavailable/);assert.strictEqual(inspect.context.test.state().overviewHeading,'Network switch in progress','mainnet auth failure must not render portfolio unavailable after invalidation');
 const connect=harness({portfolioResponse:deferred()});connect.context.test.setAuthenticated(key,'phantom',connect.provider);const connectionRun=connect.context.test.connectWallet('phantom');await new Promise(resolve=>setImmediate(resolve));connect.provider.emit('disconnect');connect.pendingChallenge.resolve({ok:true,status:200,text:async()=>JSON.stringify({message:'challenge',network:'mainnet-beta',genesisHash:MAIN})});await new Promise(resolve=>setImmediate(resolve));await assert.rejects(()=>connectionRun,/stale_wallet_continuation/);assert.notStrictEqual(connect.context.test.state().connectionTitle,'Connection failed','stale connect catch must not write connection-error UI');
 console.log('post-invalidation stale continuations runtime passed');
})().catch(error=>{console.error(error);process.exitCode=1});
