const assert=require('assert'),fs=require('fs'),vm=require('vm');
const src=fs.readFileSync('app.js','utf8');
const ctx={};vm.runInNewContext(`${src.slice(src.indexOf('function setText'),src.indexOf('async function inspect'))};this.api={renderWalletSafeguardProjection}`,ctx);
const {renderWalletSafeguardProjection}=ctx.api;
const elements={};for(const id of ['private-safeguard-review','private-safeguard-state','safeguard-cap','safeguard-cap-output'])elements[id]={id,textContent:'',value:'10000',hidden:true,classList:{toggle(c,v){this[c]=v}},addEventListener(type,fn){this[type]=fn}};
const doc={querySelector:s=>elements[s.slice(1)]};
const globals=[{targetId:'vault-1',ruleId:'global',result:'unknown'}];
const publicWire={walletId:'owner',positions:[{targetId:'vault-1',safeguards:globals}],safeguards:globals};
renderWalletSafeguardProjection({document:doc,walletAddress:'owner',portfolio:publicWire});
assert.equal(elements['private-safeguard-review'].hidden,true,'public projection hides private review');
assert.equal(elements['private-safeguard-state'].textContent,'','public projection has no private state');
const ownerPrivate={...globals[0],bindingId:'private',scope:'owner-private',result:'unknown',reason:'missing_receipt'};
const ownerWire={walletId:'owner',positions:[{targetId:'vault-1',safeguards:[globals[0],ownerPrivate]}],safeguards:[globals[0],ownerPrivate]};
renderWalletSafeguardProjection({document:doc,walletAddress:'owner',portfolio:ownerWire});
assert.equal(elements['private-safeguard-review'].hidden,false,'owner sees authoritative private review');
assert(/unknown|missing_receipt/i.test(elements['private-safeguard-state'].textContent),'owner sees exact backend state/reason');
renderWalletSafeguardProjection({document:doc,walletAddress:'other',portfolio:ownerWire});
assert.equal(elements['private-safeguard-review'].hidden,true,'wrong owner hides private review');
console.log('private safeguard visibility runtime passed');
