const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('app.html','utf8');
const css=fs.readFileSync('styles.css','utf8');
const footer=html.match(/<div class="sidebar-bottom">[\s\S]*?<\/div><\/aside>/);
assert(footer,'Sidebar footer must contain network status and status link');
assert.match(footer[0],/<span id="health" class="network live"><i><\/i> Mainnet live<\/span>/,'Mainnet live must remain in sidebar footer');
assert.match(footer[0],/<a class="status-link"[^>]*href="https:\/\/status\.kelvara\.xyz\/?"/,'status link target missing');
assert.match(footer[0],/target="_blank"/,'status page should open separately');
assert.match(footer[0],/rel="noreferrer"/,'external link isolation missing');
assert.match(footer[0],/aria-label="System status"/,'accessible label missing');
assert.match(footer[0],/title="System status"/,'tooltip missing');
assert(!footer[0].includes('>Health<'),'visible Health text must be absent');
assert.match(css,/\.sidebar-bottom\{[^}]*margin-top:auto[^}]*display:flex[^}]*justify-content:space-between[^}]*\}/,'footer must be pinned by flex spacer');
assert.match(css,/\.status-link\{[^}]*width:30px[^}]*height:30px[^}]*\}/,'status icon must be 30px');
console.log('sidebar status icon: ok');
