const assert=require('assert'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync('app.js','utf8');
const MAIN='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d';
const key='SessionInvalidationWallet111111111111111111111111111111';
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject}}
function store(seed={}){const data=new Map(Object.entries(seed));return{data,getItem(k){return data.has(k)?data.get(k):null},setItem(k,v){data.set(k,String(v))},removeItem(k){data.delete(k)}}}
function node(){return{classList:{add(){},remove(){},toggle(){}},style:{setProperty(){}},dataset:{},value:'',checked:false,disabled:false,textContent:'',innerHTML:'',onclick:null,onchange:null,onkeydown:null,addEventListener(){},setAttribute(){},replaceChildren(){},closest(){return this},getBoundingClientRect(){return{left:0,top:0,width:1,height:1}}}}
function harness({status=200,body={positions:[],safeguards:[],protocolStatuses:[],coverage:{}},session=true,publicView=false}={}){
 const sessionStorage=store({kelvara_network_context:'mainnet-beta',...(session?{kelvara_app_session:JSON.stringify({wallet:key,source:'phantom',token:'trusted-token',network:'mainnet-beta',genesisHash:MAIN})}:{})}),localStorage=store(),nodes=new Map();
 const events={},pending=deferred(),redirects=[],calls=[];
 const provider={isConnected:true,publicKey:{toString:()=>key},on(name,handler){events[name]=handler},emit(name,value){events[name]?.(value)},async disconnect(){events.disconnect?.();return undefined}};
 const document={body:node(),querySelector(selector){if(selector.startsWith('#')){if(!nodes.has(selector.slice(1)))nodes.set(selector.slice(1),node());return nodes.get(selector.slice(1))}return node()},querySelectorAll(){return[]},createElement:node,addEventListener(){}};
 const location={hostname:'localhost',hash:'',replace(url){redirects.push(url)}};
 const context={document,window:{addEventListener(){},scrollTo(){},phantom:{solana:provider}},location,localStorage,sessionStorage,fetch:async(url,options)=>{calls.push([url,options||{}]);if(url.includes('/portfolio/')||url.includes('/inspect/')){if(body===pending)return pending.promise;return{ok:status>=200&&status<300,status,text:async()=>JSON.stringify(body)}}return{ok:true,status:200,text:async()=>JSON.stringify({})}},setTimeout,clearTimeout,setInterval:()=>1,clearInterval,Promise,URLSearchParams,Intl,DOMParser:class{},TextEncoder,atob:()=>'',btoa:()=>'',matchMedia:()=>({matches:false}),console,animalIdenticonSvg:()=>''};
 const code=source.replace(/^import[^\n]*\n/gm,'').replace(/\ninit\(\);\s*$/,'')+`\nglobalThis.test={bindWalletEvents,disconnectWallet,inspect,request,protectionRequest,sessionBinding,setAuthenticated(address,source,p){walletAddress=address;walletSource=source;activeProvider=p;protectionToken='trusted-token';verifiedGenesisHash='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d';evidence={position:{name:'stale evidence'},authority:{status:'ok'}};portfolioState={positions:[{targetId:'stale'}]};sessionStorage.setItem(APP_SESSION_KEY,JSON.stringify({wallet:address,source,token:'trusted-token',network:CURRENT_NETWORK,genesisHash:'5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d'}))},state(){return{walletAddress,walletSource,activeProvider,evidence,portfolioState,protectionToken,protectionStatus,redirects:location.replace}}};`;
 vm.runInNewContext(code,context,{filename:'app.js'});
 context.test.setAuthenticated(publicView?key:'old-'+key,'phantom',provider);if(!session)context.sessionStorage.removeItem('kelvara_app_session');if(publicView){context.test.setAuthenticated(key,'address',null);context.sessionStorage.removeItem('kelvara_app_session');}
 return{context,provider,events,sessionStorage,localStorage,redirects,calls,pending,nodes};
}
function assertCleared(h){const state=h.context.test.state();assert.strictEqual(state.walletAddress,null,'wallet address cleared');assert.strictEqual(state.walletSource,null,'wallet source cleared');assert.strictEqual(state.activeProvider,null,'active provider cleared');assert.strictEqual(state.evidence,null,'evidence cleared');assert.strictEqual(state.portfolioState,null,'portfolio state cleared');assert.strictEqual(state.protectionToken,null,'auth token cleared');assert.strictEqual(h.sessionStorage.getItem('kelvara_app_session'),null,'app session cleared');assert.deepStrictEqual(h.redirects,['/?wallet_error=session'],'one canonical session redirect')}
(async()=>{
 for(const event of ['disconnect','accountChanged']){const h=harness();h.context.test.bindWalletEvents(h.provider);if(event==='disconnect')h.provider.emit(event);else h.provider.emit(event,{toString:()=> 'different-wallet'});assertCleared(h)}
 const missing=harness({session:false});await assert.rejects(()=>missing.context.test.request('/api/portfolio/'+key),/network_session_binding_missing/);assertCleared(missing);
 for(const raw of ['{malformed','null']){const h=harness();h.sessionStorage.setItem('kelvara_app_session',raw);await assert.rejects(()=>h.context.test.request('/api/portfolio/'+key),/network_session_binding_missing/);assertCleared(h)}
 for(const responseStatus of [401,403]){const h=harness({status:responseStatus,body:{error:'expired'}});await assert.rejects(()=>h.context.test.request('/api/portfolio/'+key),error=>error.status===responseStatus);assertCleared(h)}
 const explicit=harness();await explicit.context.test.disconnectWallet();assertCleared(explicit);assert.strictEqual(explicit.redirects.length,1,'provider event inside explicit disconnect does not duplicate navigation');
 const race=harness({body:harness});const inspect=race.context.test.inspect();race.provider.isConnected=false;race.pending.resolve({ok:true,status:200,text:async()=>JSON.stringify({positions:[],safeguards:[],protocolStatuses:[],coverage:{}})});await assert.rejects(()=>inspect,/wallet_session_ended|stale_inspection/);assertCleared(race);
 const public401=harness({status:401,body:{error:'public denied'},publicView:true});await assert.rejects(()=>public401.context.test.request('/api/inspect/'+key),error=>error.status===401);assert.deepStrictEqual(public401.redirects,[],'public-address 401 does not logout');assert.strictEqual(public401.context.test.state().walletSource,'address','public address remains viewable');
 for(const responseStatus of [404,503]){const h=harness({status:responseStatus,body:{error:'unavailable'}});await assert.rejects(()=>h.context.test.request('/api/portfolio/'+key),error=>error.status===responseStatus);assert.deepStrictEqual(h.redirects,[],'non-auth outage does not logout');assert.strictEqual(h.context.test.state().walletAddress,'old-'+key,'session remains on non-auth outage')}
 console.log('authenticated session invalidation runtime passed');
})().catch(error=>{console.error(error);process.exitCode=1});
