import assert from 'node:assert';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync('index.html','utf8');
const start=html.indexOf('<script data-wallet-module>'),end=html.indexOf('</script>',start)+9;
const module=html.slice(start,end).replace(/^<script[^>]*>|<\/script>$/g,'');
const MAIN='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d', DEV='EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG', key='11111111111111111111111111111111';
const stale={kelvara_handoff:'stale-handoff',kelvara_app_session:'stale-session',kelvara_auth_token:'stale-token',kelvara_prod_monitor_wallet:'stale-wallet'};
function store(seed={}){const data=new Map(Object.entries(seed));return{data,getItem:k=>data.has(k)?data.get(k):null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)}}
function el(){return{hidden:false,textContent:'',onclick:null,querySelectorAll:s=>s==='[data-network]'?[{dataset:{network:'mainnet-beta'},onclick:null},{dataset:{network:'devnet'},onclick:null}]:s==='[data-wallet]'?[{dataset:{wallet:'phantom'},onclick:null}]:[]}}
function response(spec){return{ok:spec.status===undefined||spec.status>=200&&spec.status<300,json:async()=>{if(spec.jsonError)throw Error('bad json');return spec.body}}}
async function run({network,challenge={message:'challenge',network:'mainnet-beta',genesisHash:MAIN},session={token:'token',network:'mainnet-beta',genesisHash:MAIN},challengeStatus=200,verifyStatus=200,inspectStatus=200,challengeJsonError=false,verifyJsonError=false,inspectJsonError=false,inspectBody={position:{}},seed=true}={}){
 const seedData=seed?{...stale,kelvara_network_context:network}:{};const sessionStorage=store(seedData),localStorage=store(seed?{kelvara_prod_monitor_wallet:'stale-wallet',kelvara_wallet_gate_ip:JSON.stringify({ip:'185.78.133.77',expiresAt:Date.now()+60000})}:{}),walletButton={dataset:{wallet:'phantom'},onclick:null},nodes=new Map(['wallet-selector','network-selector','network-selector-status','wallet-selector-message','wallet-chip','wallet-chip-address','wallet-disconnect','wallet-selector-close','realm-label'].map(id=>[id,el()]));
 nodes.get('wallet-selector').querySelectorAll=()=>[walletButton];nodes.get('network-selector').querySelectorAll=()=>[];const calls=[];let signs=0,redirect;
 const provider={isConnected:true,publicKey:{toString:()=>key},connect:async()=>({publicKey:provider.publicKey}),signMessage:async()=>{signs++;return{signature:new Uint8Array([1,2,3])}},on(){},disconnect:async()=>{}};
 const context={window:{phantom:{solana:provider}},sessionStorage,localStorage,location:{replace:u=>redirect=u},document:{querySelector:s=>nodes.get(s.slice(1))||{querySelectorAll:()=>[],addEventListener(){}},querySelectorAll:s=>s==='[data-wallet]'?[walletButton]:[],addEventListener(){}},fetch:async(url,opts)=>{calls.push([url,opts]);if(url.startsWith('https://api.ipify.org'))return response({body:{ip:'185.78.133.77'}});if(url.endsWith('/challenge'))return response({status:challengeStatus,body:challenge,jsonError:challengeJsonError});if(url.endsWith('/verify'))return response({status:verifyStatus,body:session,jsonError:verifyJsonError});if(url.includes('/inspect/')||url.includes('/portfolio/'))return response({status:inspectStatus,body:inspectBody,jsonError:inspectJsonError});throw Error('unexpected fetch')},TextEncoder,btoa:s=>Buffer.from(s,'binary').toString('base64'),console};
 vm.runInNewContext(module,context);await walletButton.onclick();await new Promise(r=>setImmediate(r));return{calls,signs,redirect,sessionStorage,localStorage};
}
function assertCleared(r){for(const k of Object.keys(stale)){const storage=k==='kelvara_prod_monitor_wallet'?r.localStorage:r.sessionStorage;assert.strictEqual(storage.getItem(k),null,k)}}
(async()=>{
 let r=await run({network:'mainnet-beta'});assert.strictEqual(r.signs,1);assert.strictEqual(r.calls.length,4);assert.strictEqual(r.redirect,'/app.html?v=7626559');
 r=await run({network:'devnet',challenge:{message:'challenge',network:'devnet',genesisHash:DEV},session:{token:'token',network:'devnet',genesisHash:DEV},inspectBody:{network:'devnet',genesisHash:DEV,sourceStatus:'canonical_devnet_empty_read_only',positions:[],safeguards:[],protocolStatuses:[]}});assert.strictEqual(r.signs,1);assert.strictEqual(r.calls.length,4);assert.match(r.calls[3][0],/\/api\/portfolio\//);assert.strictEqual(r.redirect,'/app.html?v=7626559');
 for(const spec of [{challenge:{message:'challenge',network:'devnet',genesisHash:DEV},challengeStatus:500},{challenge:{message:'challenge',network:'devnet',genesisHash:DEV},challenge:{message:'challenge',network:'devnet',genesisHash:DEV}},{challenge:{message:'challenge',network:'mainnet-beta',genesisHash:MAIN}}]){r=await run({network:'devnet',...spec});assert.strictEqual(r.redirect,undefined);assertCleared(r)}
 for(const bad of [{network:'mainnet-beta',genesisHash:MAIN,wallet:key,position:null,authority:null,sourceStatus:'canonical_devnet_empty_read_only'},{network:'devnet',genesisHash:'wrong',wallet:key,position:null,authority:null,sourceStatus:'canonical_devnet_empty_read_only'},{network:'devnet',genesisHash:DEV,wallet:'wrong',position:null,authority:null,sourceStatus:'canonical_devnet_empty_read_only'},{network:'devnet',genesisHash:DEV,wallet:key,position:{},authority:null,sourceStatus:'canonical_devnet_empty_read_only'}]){r=await run({network:'devnet',challenge:{message:'challenge',network:'devnet',genesisHash:DEV},session:{token:'token',network:'devnet',genesisHash:DEV},inspectBody:bad});assert.strictEqual(r.redirect,undefined);assertCleared(r)}
 console.log('root auth dynamic mainnet and Devnet matrix passed');
})().catch(error=>{console.error(error);process.exitCode=1});
