const assert=require('assert'),fs=require('fs'),vm=require('vm');
const app=fs.readFileSync('app.js','utf8'),html=fs.readFileSync('app.html','utf8');
const MAIN='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d',DEV='EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG',WALLET='AuditWallet111111111111111111111111111111111111';
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject}}
function node(id){return {id,textContent:'',innerHTML:'',value:'',hidden:false,disabled:false,dataset:{},className:'',style:{},classList:{add(){},remove(){},toggle(){}},setAttribute(n,v){this[n]=v},getAttribute(n){return this[n]},replaceChildren(){},appendChild(){},addEventListener(){},querySelectorAll(){return[]},closest(){return this}}}
function harness(network='mainnet-beta'){
 const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);const els=new Map([...new Set(ids)].map(id=>[id,node(id)]));
 for(const id of ['network-selector','wallet-selector'])els.get(id).querySelectorAll=()=>[];
 const session=new Map([['kelvara_network_context',network]]),local=new Map(),listeners={},challenge=deferred(),verify=deferred();let fetches=[],disconnects=0,connects=0,signs=0;
 const provider={isConnected:true,publicKey:{toString:()=>WALLET},async connect(){connects++;return{publicKey:this.publicKey}},async disconnect(){disconnects++},async signMessage(){signs++;return Uint8Array.of(1)},on(){}};
 const response=(body)=>({ok:true,status:200,text:async()=>JSON.stringify(body),json:async()=>body});
 const context={normalizeNetwork:value=>value==='mainnet-beta'||value==='devnet'?value:null,DEVNET_GENESIS:DEV,validateDevnetPortfolio:value=>value,projectDevnetView:()=>({emptyLabel:'No Devnet positions',positionLabel:'No positions detected',networkLabel:'Devnet'}),devnetRequest:(address,token)=>({path:'/api/portfolio/'+address,headers:{}}),document:{querySelector(s){if(s.startsWith('#'))return els.get(s.slice(1))||node(s.slice(1));return node(s)},querySelectorAll(){return[]},createElement:()=>node('created'),addEventListener(n,f){(listeners[n]??=[]).push(f)}},window:{phantom:{solana:provider},addEventListener(){},scrollTo(){}},location:{hash:'',reload(){},replace(){}},sessionStorage:{getItem(k){return session.get(k)||null},setItem(k,v){session.set(k,String(v))},removeItem(k){session.delete(k)}},localStorage:{getItem(k){return local.get(k)||null},setItem(k,v){local.set(k,String(v))},removeItem(k){local.delete(k)}},fetch:async(url,options)=>{fetches.push([url,options]);if(url.endsWith('/api/auth/challenge'))return challenge.promise;if(url.endsWith('/api/auth/verify'))return verify.promise;return response({network,genesisHash:network==='devnet'?DEV:MAIN,sourceStatus:'canonical_devnet_empty_read_only',positions:[],safeguards:[],protocolStatuses:[]})},setTimeout,clearTimeout,setInterval:()=>1,clearInterval,Promise,URLSearchParams,Intl,DOMParser:class{},TextEncoder,atob:()=>'',btoa:s=>Buffer.from(s,'binary').toString('base64'),matchMedia:()=>({matches:false}),console,animalIdenticonSvg:()=>'',CustomEvent:function(type,init){this.type=type;this.detail=init.detail}};
 const source=app.replace(/^import[^\n]*\n/gm,'').replace(/\ninit\(\);\s*$/,'')+'\nthis.exportAudit={connectWallet,authenticateProtection,inspect,armProtection,switchNetwork,clearNetworkScopedState,renderDevnetReadOnly,setAuthFixture:(address,source,provider,token)=>{walletAddress=address;walletSource=source;activeProvider=provider;protectionToken=token}};';vm.runInNewContext(source,context,{filename:'app.js'});
 return {context,els,session,local,provider,challenge,verify,fetches,counts:()=>({disconnects,connects,signs})};
}
async function settle(){for(let i=0;i<4;i++)await new Promise(resolve=>setImmediate(resolve))}
(async()=>{
 // RED: connectWallet must not sign/save after a network switch during challenge.
 {const h=harness();const pending=h.context.exportAudit.connectWallet('phantom');await settle();assert.equal(h.counts().connects,1);h.context.exportAudit.switchNetwork('devnet');h.challenge.resolve({ok:true,status:200,text:async()=>JSON.stringify({message:'challenge',network:'mainnet-beta',genesisHash:MAIN}),json:async()=>({message:'challenge',network:'mainnet-beta',genesisHash:MAIN})});h.verify.resolve({ok:true,status:200,text:async()=>JSON.stringify({token:'stale-token',network:'mainnet-beta',genesisHash:MAIN}),json:async()=>({token:'stale-token',network:'mainnet-beta',genesisHash:MAIN})});await pending;await settle();assert.equal(h.counts().signs,0,'stale connect continuation must not sign');assert.equal(h.session.get('kelvara_app_session'),undefined,'stale connect continuation must not save session')}
 // RED: authenticateProtection must not install a token after verify crosses a switch.
 {const h=harness();h.context.exportAudit.setAuthFixture(WALLET,'phantom',h.provider,null);const pending=h.context.exportAudit.authenticateProtection();await settle();h.challenge.resolve({ok:true,status:200,text:async()=>JSON.stringify({message:'challenge',network:'mainnet-beta',genesisHash:MAIN}),json:async()=>({message:'challenge',network:'mainnet-beta',genesisHash:MAIN})});await settle();h.context.exportAudit.switchNetwork('devnet');h.verify.resolve({ok:true,status:200,text:async()=>JSON.stringify({token:'stale-token',network:'mainnet-beta',genesisHash:MAIN}),json:async()=>({token:'stale-token',network:'mainnet-beta',genesisHash:MAIN})});await assert.rejects(pending,/stale_wallet_continuation/);assert.equal(h.context.protectionToken,null,'stale verify continuation must not install token')}
 // RED: stale Devnet inspection must not replace switch UI with an unavailable error.
 {const h=harness('devnet');h.session.set('kelvara_app_session',JSON.stringify({wallet:WALLET,source:'phantom',token:'token',network:'devnet',genesisHash:DEV}));h.context.exportAudit.setAuthFixture(WALLET,'phantom',h.provider,'token');const responseGate=deferred();h.context.fetch=async()=>responseGate.promise;const pending=h.context.exportAudit.inspect();await settle();h.context.exportAudit.switchNetwork('mainnet-beta');assert.equal(h.els.get('overview-heading').textContent,'Network switch in progress');responseGate.resolve({ok:true,status:200,text:async()=>JSON.stringify({network:'devnet',genesisHash:DEV,sourceStatus:'canonical_devnet_empty_read_only',positions:[],safeguards:[],protocolStatuses:[]})});await assert.rejects(pending,/stale_inspection/);assert.equal(h.els.get('overview-heading').textContent,'Network switch in progress','stale inspection must not render unavailable state')}
 // RED: pending nonce records require wallet, network, and genesis binding.
 {const source=app.slice(app.indexOf('async function armProtection'),app.indexOf('async function fastClose'));assert.match(source,/pending\.network===CURRENT_NETWORK/);assert.match(source,/pending\.genesisHash===verifiedGenesisHash/);assert.match(source,/network:CURRENT_NETWORK/);assert.match(source,/genesisHash:verifiedGenesisHash/)}
 // RED: every Devnet mutation control is disabled, not only the first four.
 {const mutationIds=['arm-protection','prepare-evacuation','fast-close','revoke-protection','activate','simulate-evacuation','sign-evacuation'].filter(id=>harness('devnet').els.has(id));const h=harness('devnet');h.context.exportAudit.renderDevnetReadOnly({network:'devnet',genesisHash:DEV,sourceStatus:'canonical_devnet_empty_read_only',positions:[],safeguards:[],protocolStatuses:[]});for(const id of mutationIds)assert.equal(h.els.get(id).disabled,true,id+' must be disabled on Devnet')}
 console.log('audit blocker regressions passed');
})().catch(error=>{console.error(error);process.exitCode=1});
