const assert=require('assert'),fs=require('fs'),vm=require('vm');
const app=fs.readFileSync('app.js','utf8'),html=fs.readFileSync('app.html','utf8');
assert(html.includes('id="network-control"'),'authenticated app exposes network control');assert(html.includes('id="network-selector"'),'authenticated app exposes network chooser');assert(html.includes('data-network="mainnet-beta"')&&html.includes('data-network="devnet"'),'chooser exposes both networks');assert(!html.includes('id="account-network">Mainnet</dd>'),'account placeholder is neutral');assert(!app.includes('p.protocol||"Kamino"} · Solana Mainnet'),'position labels are not hard-coded');
const source=app.replace(/^import[^\n]*\n/gm,'').replace(/\ninit\(\);\s*$/,'\nthis.exportTests={bindNetworkControl,renderNetworkLabel,renderPosition,switchNetwork,connectWallet};');
const MAIN='5eykt4UsvFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d',DEV='EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG',wallet='WalletAppSwitch111111111111111111111111111111111111';
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject}}
function node(id,attrs={}){return Object.assign({id,textContent:'',innerHTML:'',value:'',hidden:false,className:'',disabled:false,dataset:{},style:{},classList:{add(){},remove(){},toggle(){}},setAttribute(name,value){this[name]=value},getAttribute(name){return this[name]},appendChild(){},replaceChildren(){},addEventListener(){},querySelectorAll(){return[]},closest(){return null}},attrs)}
function boot(initial='mainnet-beta',disconnectMode='pending'){
 const genesis=initial==='devnet'?DEV:MAIN,data=new Map([['kelvara_network_context',initial],['kelvara_app_session',JSON.stringify({wallet,source:'phantom',token:'token',network:initial,genesisHash:genesis})],['kelvara_auth_token','auth']]),local=new Map([['kelvara_prod_monitor_wallet','wallet']]),ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]),els=new Map(ids.map(id=>[id,node(id)]));els.get('network-selector').hidden=true;els.get('connected-workspace').hidden=false;
 const networks=['mainnet-beta','devnet'].map(network=>node('',{dataset:{network}}));els.get('network-selector').querySelectorAll=()=>networks;els.get('wallet-selector').querySelectorAll=()=>[];
 let connectCalls=0,signCalls=0,fetchCalls=0,reloadCalls=0,disconnectCalls=0,gate=deferred(),timers=[];const testSetTimeout=(fn,ms)=>{const timer={fn,ms};timers.push(timer);return timer};const testClearTimeout=timer=>{timers=timers.filter(item=>item!==timer)};
 const provider={isConnected:true,publicKey:{toString:()=>wallet},async connect(){connectCalls++;return{publicKey:this.publicKey}},async signMessage(){signCalls++;return Uint8Array.of(1)},async disconnect(){disconnectCalls++;return disconnectMode==='timeout'?new Promise(()=>{}):gate.promise},on(){}};
 const redirects=[];const ctx={normalizeNetwork:v=>v==='mainnet-beta'||v==='devnet'?v:null,document:{querySelector:s=>s.startsWith('#')?(els.get(s.slice(1))||node(s.slice(1))):node(s),querySelectorAll:()=>[],createElement:()=>node('created'),addEventListener(){}},window:{phantom:{solana:provider},addEventListener(){},scrollTo(){}},location:{hash:'',reload(){reloadCalls++},replace(url){redirects.push(url)}},sessionStorage:{getItem:k=>data.has(k)?data.get(k):null,setItem(k,v){data.set(k,String(v))},removeItem(k){data.delete(k)}},localStorage:{getItem:k=>local.has(k)?local.get(k):null,setItem(k,v){local.set(k,String(v))},removeItem(k){local.delete(k)}},fetch:async()=>{fetchCalls++;return{ok:true,text:async()=>JSON.stringify({}),json:async()=>({})}},setTimeout:testSetTimeout,clearTimeout:testClearTimeout,setInterval:()=>1,clearInterval:()=>{},Promise,URLSearchParams,Intl,DOMParser:class{},TextEncoder,atob:()=>'',btoa:()=>'',matchMedia:()=>({matches:false}),console,animalIdenticonSvg:()=>''};
 ctx.__testProvider=provider;vm.runInNewContext(source,ctx,{filename:'app.js'});vm.runInNewContext('activeProvider=__testProvider;walletAddress="'+wallet+'";walletSource="phantom";',ctx);return{ctx,els,networks,data,local,gate,redirects,advance(ms){for(const timer of timers.splice(0)){if(timer.ms<=ms)timer.fn()}},counts:()=>({connectCalls,signCalls,fetchCalls,reloadCalls,disconnectCalls})};
}
(async()=>{const h=boot();h.ctx.exportTests.bindNetworkControl();h.ctx.exportTests.renderNetworkLabel();assert.strictEqual(h.els.get('network-context-label').textContent,'Mainnet');assert.strictEqual(h.els.get('network-selector').hidden,true);h.els.get('network-context-label').onclick();assert.strictEqual(h.els.get('network-selector').hidden,false);h.els.get('network-selector-close').onclick();assert.strictEqual(h.els.get('network-selector').hidden,true);
 const before=h.counts();h.ctx.exportTests.switchNetwork('devnet');assert.strictEqual(h.counts().disconnectCalls,1);assert.strictEqual(h.counts().reloadCalls,0);for(const k of ['kelvara_handoff','kelvara_app_session','kelvara_auth_token'])assert(!h.data.has(k));assert(!h.local.has('kelvara_prod_monitor_wallet'));await h.ctx.exportTests.connectWallet('phantom');assert.strictEqual(h.counts().connectCalls,before.connectCalls);assert.strictEqual(h.counts().signCalls,before.signCalls);assert.strictEqual(h.counts().fetchCalls,before.fetchCalls);h.gate.resolve();await new Promise(r=>setImmediate(r));assert.strictEqual(h.counts().reloadCalls,1);
 const d=boot('devnet');d.ctx.exportTests.renderNetworkLabel();assert.strictEqual(d.els.get('network-context-label').textContent,'Devnet');d.ctx.exportTests.renderPosition({position:{name:'Devnet position',protocol:'Kamino',underlyingAmount:1,asset:'USDG',totalShares:1,stakedShares:1,unstakedShares:0,tokensPerShare:1},authority:{},observedAt:'2026-01-01T00:00:00Z'});assert.strictEqual(d.els.get('position-network').textContent,'Devnet');const m=boot('mainnet-beta');m.ctx.exportTests.renderPosition({position:{name:'Mainnet position',protocol:'Kamino',underlyingAmount:1,asset:'USDG',totalShares:1,stakedShares:1,unstakedShares:0,tokensPerShare:1},authority:{},observedAt:'2026-01-01T00:00:00Z'});assert.strictEqual(m.els.get('position-network').textContent,'Mainnet');for(const mode of ['rejected','timeout']){const r=boot('devnet',mode);r.ctx.exportTests.switchNetwork('mainnet-beta');if(mode==='rejected')r.gate.reject(Error('disconnect failed'));else r.advance(10001);await new Promise(x=>setImmediate(x));assert.strictEqual(r.els.get('connected-workspace').hidden,true,`${mode} keeps protected workspace hidden`);await r.ctx.exportTests.connectWallet('phantom');assert.strictEqual(r.counts().connectCalls,0);assert.strictEqual(r.counts().signCalls,0);assert.strictEqual(r.counts().fetchCalls,0);assert.strictEqual(r.counts().reloadCalls,0);assert.deepStrictEqual(r.redirects,['/?wallet_error=session'],`${mode} invalidates session once`) }
 const same=boot();same.ctx.exportTests.switchNetwork('mainnet-beta');assert.strictEqual(same.counts().disconnectCalls,0);console.log('authenticated app network chooser and dynamic labels passed');})().catch(e=>{console.error(e);process.exitCode=1});
