const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('app.html','utf8'), app=fs.readFileSync('app.js','utf8');
assert(html.includes('href="#governance"'),'Governance route missing');
const source=app.replace(/^import[^\n]*\n/gm,'').replace(/\ninit\(\);\s*$/,'')+'\nthis.test={renderGovernance,governanceUrl};';
function node(){return {textContent:'',innerHTML:'',hidden:false,className:'',classList:{add(){},remove(){},toggle(){}},setAttribute(){},appendChild(){},addEventListener(){},querySelectorAll(){return[]}}}
const nodes=new Map();const document={querySelector(s){if(!nodes.has(s))nodes.set(s,node());return nodes.get(s)},querySelectorAll(){return[]},createElement(){return node()},addEventListener(){}};
const context={document,window:{addEventListener(){},scrollTo(){}},location:{hostname:'localhost',hash:''},sessionStorage:{getItem(){return 'mainnet-beta'}},localStorage:{},normalizeNetwork:v=>v,animalIdenticonSvg:()=>'',Intl,Date,fetch:async()=>({}),setInterval(){return 1},clearInterval(){},setTimeout,clearTimeout,matchMedia:()=>({matches:false}),console};
vm.runInNewContext(source,context);
const fixture={schemaVersion:'customer-governance/v1',network:'mainnet-beta',freshness:{state:'fresh',observedAt:'2026-10-09T10:00:00Z',finalizedSlot:123},wallets:[{address:'Wallet<unsafe>',vaults:[{identity:{provider:'squads',generation:'v4',multisigAddress:'Multi',vaultIndex:0,vaultAddress:'Vault'},display:{name:null},membership:{role:'member',permissions:['vote'],threshold:2,memberCount:3},requiresAttention:[{id:'a1',status:'active',decodedIntent:{summary:'Transfer <script>alert(1)</script>'},approvalProgress:{approved:1,threshold:2},userStatus:'approval_required',proposer:'Prop',finalizedSlot:121,sourceSignature:'Sig',instructions:[{program:'system',intent:'Transfer'}],provenance:{decoder:'squads-v4'}}],currentActions:[],recentChanges:Array.from({length:11},(_,i)=>({id:'h'+i,status:'executed',decodedIntent:{summary:'Change '+i}})),nextHistoryCursor:'cursor-1'}]}],warnings:[]};
context.test.renderGovernance(fixture);assert(nodes.get('#governance-content').innerHTML.includes('Transfer &lt;script&gt;alert(1)&lt;/script&gt;'),'XSS-safe text');assert(nodes.get('#governance-content').innerHTML.includes('Requires attention'),'attention rendered');assert(nodes.get('#governance-content').innerHTML.includes('Recent changes'),'history rendered');console.log('governance runtime ok');
