const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('app.html','utf8'), app=fs.readFileSync('app.js','utf8');
assert(html.includes('href="#governance"'),'Governance route missing');
const source=app.replace(/^import[^\n]*\n/gm,'').replace(/\ninit\(\);\s*$/,'')+'\nthis.test={renderGovernance,governanceUrl,mergeGovernanceHistory,mergeGovernancePage,loadGovernance,clearGovernance};';
function node(tag='div'){const n={tagName:tag,textContent:'',innerHTML:'',hidden:false,className:'',children:[],dataset:{},classList:{add(){},remove(){},toggle(){}},setAttribute(name,value){n[name]=value},appendChild(child){n.children.push(child);return child},append(...children){children.forEach(child=>n.appendChild(child))},replaceChildren(...children){n.children=[];n.append(...children)},addEventListener(){},querySelectorAll(){return[]}};return n}
const nodes=new Map();const document={querySelector(s){if(!nodes.has(s))nodes.set(s,node());return nodes.get(s)},querySelectorAll(){return[]},createElement(){return node()},addEventListener(){}};
const context={document,window:{addEventListener(){},scrollTo(){}},location:{hostname:'localhost',hash:''},sessionStorage:{getItem(){return 'mainnet-beta'}},localStorage:{},normalizeNetwork:v=>v,animalIdenticonSvg:()=>'',Intl,Date,fetch:async()=>({}),setInterval(){return 1},clearInterval(){},setTimeout,clearTimeout,matchMedia:()=>({matches:false}),console};
vm.runInNewContext(source,context);
const fixture={schemaVersion:'customer-governance/v1',network:'mainnet-beta',freshness:{state:'fresh',observedAt:'2026-10-09T10:00:00Z',finalizedSlot:123},wallets:[{address:'Wallet<unsafe>',vaults:[{identity:{provider:'squads',generation:'v4',multisigAddress:'Multi',vaultIndex:0,vaultAddress:'Vault'},display:{name:null},membership:{role:'member',permissions:['vote'],threshold:2,memberCount:3},requiresAttention:[{id:'a1',status:'active',decodedIntent:{summary:'Transfer <script>alert(1)</script>'},approvalProgress:{approved:1,threshold:2},userStatus:'approval_required',proposer:'Prop',finalizedSlot:121,sourceSignature:'Sig',instructions:[{program:'system',intent:'Transfer'}],provenance:{decoder:'squads-v4'}}],currentActions:[{id:'current-1',status:'active',decodedIntent:{summary:'Pending approval action'},approvalProgress:{approved:1,threshold:2},userStatus:'approval_required',proposer:'Current proposer',createdSlot:150,sourceSignature:'CurrentSig'}],recentChanges:Array.from({length:11},(_,i)=>({id:'h'+i,status:'executed',decodedIntent:{summary:'Change '+i}})),nextHistoryCursor:'cursor-1'}]}],warnings:[]};
function textTree(item){return `${item.textContent||''}${(item.children||[]).map(textTree).join('')}`}function htmlTree(item){return `${item.innerHTML||''}${(item.children||[]).map(htmlTree).join('')}`}context.test.renderGovernance(fixture);const rendered=textTree(nodes.get('#governance-content'));assert(rendered.includes('Transfer <script>alert(1)</script>'),'XSS payload remains text');assert(!htmlTree(nodes.get('#governance-content')).includes('<script>alert(1)</script>'),'XSS markup never created');assert(rendered.includes('Requires attention'),'attention rendered');assert(rendered.includes('Current actions'),'current actions rendered');assert(rendered.includes('No current actions.')===false,'active current action must be visible');assert(rendered.includes('Recent changes'),'history rendered');
const old=[{address:'w1',vaults:[{identity:{vaultAddress:'v1'},recentChanges:[{id:'old-1'}]}]},{address:'w2',vaults:[{identity:{vaultAddress:'v2'},recentChanges:[{id:'old-2'}]}]}];
const page=[{address:'w2',vaults:[{identity:{vaultAddress:'v2'},recentChanges:[{id:'new-2'}]}]}];
const positional=context.test.mergeGovernanceHistory(old[0].vaults[0].recentChanges,page[0].vaults[0].recentChanges);assert(!positional.some(x=>x.id==='old-2'),'fixture sanity');
const sameSummary=context.test.mergeGovernanceHistory([{id:'a',decodedIntent:{summary:'same'}}],[{id:'b',decodedIntent:{summary:'same'}}]);assert.equal(sameSummary.length,2,'dedupe uses action id');
const mergedPage=context.test.mergeGovernancePage({wallets:old}, {wallets:page});assert.equal(mergedPage.wallets.length,2,'pagination preserves wallets');assert.equal(mergedPage.wallets[0].vaults[0].recentChanges[0].id,'old-1','pagination preserves unrelated vault');assert.equal(mergedPage.wallets[1].vaults[0].recentChanges.length,2,'pagination appends matching vault history');
const invalid={...fixture,wallets:[{...fixture.wallets[0],vaults:[{...fixture.wallets[0].vaults[0],requiresAttention:{bad:true}}]}]};context.test.renderGovernance(invalid);assert(textTree(nodes.get('#governance-content')).includes('Requires attention'),'non-array attention handled');
console.log('governance runtime ok');
