const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('app.html','utf8'),source=fs.readFileSync('app.js','utf8'),fixture=JSON.parse(fs.readFileSync('canonical_program_portfolio_two_vaults.json','utf8'));
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
function node(tag='div'){const classes=new Set(['hidden']);return {tagName:tag,classList:{add(...x){x.forEach(v=>classes.add(v))},remove(...x){x.forEach(v=>classes.delete(v))},toggle(x,value){if(value===undefined)value=!classes.has(x);value?classes.add(x):classes.delete(x)},contains(x){return classes.has(x)}},style:{setProperty(){}},dataset:{},children:[],value:'',checked:false,disabled:false,textContent:'',innerHTML:'',onclick:null,onchange:null,onkeydown:null,hidden:false,append(...x){this.children.push(...x)},appendChild(x){this.children.push(x)},addEventListener(){},setAttribute(k,v){this[k]=v},getAttribute(k){return this[k]},replaceChildren(...x){this.children=x},closest(){return this},querySelectorAll(){return[]},getBoundingClientRect(){return {left:0,top:0,width:1,height:1}}};}
const nodes=new Map([...ids].map(id=>[id,node()]));
const rows=[];const list=nodes.get('portfolio-positions');list.replaceChildren=(...x)=>{rows.splice(0);rows.push(...x);list.children=rows};
const document={querySelector(s){if(s.startsWith('#'))return nodes.get(s.slice(1))||node();return node()},querySelectorAll(s){if(s==='#portfolio-positions .position-row')return rows;return[]},createElement:node,addEventListener(){}};
const calls=[];const wallet='Wallet111111111111111111111111111111111';const walletProviderMock={isConnected:true,publicKey:{toString:()=>wallet}};
const context={document,window:{addEventListener(){},scrollTo(){},phantom:{solana:walletProviderMock},location:{hostname:'localhost',hash:'',replace(){}}},location:{hostname:'localhost',hash:'',replace(){}},localStorage:{getItem(){return null},setItem(){},removeItem(){}},sessionStorage:{getItem(){return null},removeItem(){}},fetch:async(url,options={})=>{calls.push([url,options]);return {ok:true,text:async()=>JSON.stringify({})}},setTimeout,clearTimeout,setInterval,clearInterval,Promise,URLSearchParams,Intl,DOMParser:class{},TextEncoder,atob:()=>'',btoa:()=>'',matchMedia:()=>({matches:false}),console,animalIdenticonSvg:()=>'',toast(){}};
let code=source.replace(/^import[^\n]*\n/gm,'').replace(/\ninit\(\);\s*$/,'');
code+=`\nwalletAddress='${wallet}';walletSource='phantom';activeProvider={isConnected:true,publicKey:{toString:()=> 'Wallet111111111111111111111111111111111'}};protectionToken='wallet-session-only';renderPortfolio(${JSON.stringify(fixture)});const renderedRows=document.querySelectorAll('#portfolio-positions .position-row');assert.equal(renderedRows.length,2);assert.deepEqual(renderedRows.map(r=>r.children[0].textContent),['Institutional Commodity Yield','Steakhouse USDG High Yield']);assert.deepEqual(renderedRows.map(r=>r.dataset.targetId),${JSON.stringify(fixture.positions.map(p=>p.targetId))});renderedRows.forEach(row=>{row.onclick();assert.equal(row.getAttribute('aria-selected'),'true');assert.equal(selectedPositionMutationAllowed(),true);assert.equal(typeof document.querySelector('#prepare-evacuation').onclick,'function');openEvacuation();assert.equal(document.querySelector('#evacuation-modal').classList.contains('hidden'),false);toggleEvacuation(false);});`;
vm.runInNewContext(code,{...context,assert},{filename:'app.js'});
assert.equal(calls.filter(([url])=>String(url).includes('/api/protection/prepare')||String(url).includes('/api/evacuation/prepare')).length,0);
assert.equal(calls.filter(([url])=>String(url).includes('/api/portfolio/')).length,0);
console.log('two-vault canonical manual-exit DOM runtime passed');