const assert=require('assert'),fs=require('fs');
const app=fs.readFileSync('app.js','utf8'),index=fs.readFileSync('index.html','utf8'),workspace=fs.readFileSync('app.html','utf8');
const genesis='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d';
assert(index.includes("location.replace('/app.html?v=7626559')"),'published root enters workspace app');
assert(index.includes('data-network="mainnet-beta"'),'published root exposes network selection');
assert(workspace.includes('<script type="module" src="/app.js?v=7626559"></script>'),'published workspace loads versioned app.js');
assert(fs.readFileSync('CNAME','utf8').trim()==='app.kelvara.xyz','published hostname parity');
assert(app.includes('post("/api/auth/challenge",{wallet:address,network})'),'challenge sends selected network body');
assert(app.includes('headers["x-kelvara-network"]=payload.network'),'authenticated POSTs send exact network header');
assert(app.includes('post("/api/auth/verify",{wallet:address,message:challenge.message,signature,network})'),'verify sends selected network body');
assert(app.includes('challenge.genesisHash'),'challenge genesis required before signing');
assert(app.includes('session.genesisHash!==challenge.genesisHash'),'verify genesis must match challenge');
assert(app.includes('verifiedGenesisHash=session.genesisHash'),'server genesis retained');
assert(app.includes('headers["x-kelvara-genesis"]=b.genesisHash'),'protected requests bind genesis');
assert(app.includes('typeof record.genesisHash!=="string"'),'restore rejects missing genesis');
assert(app.includes('sessionStorage.removeItem("kelvara_handoff")'),'network switch clears handoff');
assert(app.includes("CURRENT_NETWORK==='devnet'"),'devnet read-only branch');
assert(app.includes('devnetRequest(address, protectionToken)'),'devnet uses bound token');
assert(app.includes('Devnet read-only portfolio loaded.'),'devnet read-only success');
assert(app.includes('if(!CURRENT_NETWORK)'),'missing network fail-closed gate');
assert(!app.includes(`genesisHash:"${genesis}"`),'production does not silently default genesis');
console.log('network session binding executable contract passed: challenge, verify, restore, protected requests, devnet, switching');
