const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('app.html','utf8'),source=fs.readFileSync('app.js','utf8'),css=fs.readFileSync('styles.css','utf8');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
assert.strictEqual(new Set(ids).size,ids.length,'duplicate DOM IDs');
assert(css.includes('.wallet-chip.header-connect'), 'explicit light-header wallet foreground contract missing');
assert(css.includes('#chip-address'), 'wallet address foreground selector missing');
assert(/\.wallet-chip\.header-connect[^}]*color:\s*#(?:1|0|[2-9a-f])/i.test(css), 'wallet foreground must be dark');
assert(css.includes('.status-pill.matches'), 'matching safeguard status must have a success style');
assert(css.includes('.status-pill.changed'), 'changed safeguard status must have a breach style');
assert(html.includes('styles.css?v=workspace-cleanup-2'), 'stylesheet cache must be bumped');
for(const stale of ['Selected position','No verified position loaded.','Unknown','Not loaded','Fast close','Evidence observed'])assert(!html.includes(stale),`stale customer copy: ${stale}`);
for(const required of ['positions','USDG','Safeguards','Protection','Provider','Network','Session'])assert(html.includes(required),`missing workspace fact: ${required}`);
for(const label of ['Current authority','Configured baseline','Observed','Program ID','ProgramData account'])assert(html.includes(`<dt>${label}</dt>`),`missing safeguard evidence label: ${label}`);

function makeElement(id){return {id,textContent:'',innerHTML:'',className:'',hidden:false,disabled:false,onclick:null,classList:{toggle(c,v){this[c]=v===undefined?!this[c]:v},add(c){this[c]=true},remove(c){this[c]=false}},setAttribute(name,value){this[name]=value},replaceChildren(){},closest(){return this}}}
const els=Object.fromEntries(ids.map(id=>[id,makeElement(id)]));
els['position-tabs']=makeElement('position-tabs');
const generic=makeElement('generic');
const document={querySelector(selector){if(selector.startsWith('#'))return els[selector.slice(1)]||null;if(selector==='main')return generic;return selector==='.position-tabs'?els['position-tabs']:generic},querySelectorAll(selector){if(selector==='[id^=position-subpane-]')return ['overview','safeguards','activity','protection'].map(x=>els[`position-subpane-${x}`]||makeElement(x));return []},addEventListener(){}};
const sessionStore={kelvara_network_context:'mainnet-beta'};const localStore={};const provider={isConnected:true,publicKey:{toString:()=>"wallet"},async connect(){return {publicKey:this.publicKey}}};
const context={normalizeNetwork(value){return value==='mainnet-beta'||value==='devnet'?value:null},document,window:{addEventListener(){},scrollTo(){},phantom:{solana:provider}},location:{hostname:'localhost',hash:'',replace(){}},localStorage:{getItem(key){return localStore[key]??null},setItem(key,value){localStore[key]=String(value)},removeItem(key){delete localStore[key]}},sessionStorage:{getItem(key){return sessionStore[key]??null},setItem(key,value){sessionStore[key]=String(value)},removeItem(key){delete sessionStore[key]}},fetch:async()=>({ok:true,json:async()=>({})}),setTimeout,clearTimeout,setInterval:()=>1,clearInterval,Promise,URLSearchParams,Intl,DOMParser:class{},TextEncoder,atob:()=>'',btoa:()=>'',matchMedia:()=>({matches:false}),console,animalIdenticonSvg:()=>''};
const code=source.replace(/^import[^\n]*\n/gm,'').replace(/\ninit\(\);\s*$/,'')+'\nthis.renderOverview=renderOverview;this.renderPosition=renderPosition;this.renderAuthority=renderAuthority;this.renderProtection=renderProtection;this.loadProtection=loadProtection;this.inspect=inspect;this.init=init;this.setProtectionToken=value=>protectionToken=value;this.setProtectionRequest=value=>protectionRequest=value;this.setWalletForTest=()=>{walletAddress="wallet";walletSource="address"};';
vm.runInNewContext(code,context,{filename:'app.js'});
context.renderOverview({position:{name:'Steakhouse USDG High Yield',underlyingAmount:'0.131061'},authority:{status:'active',current:'GzFg…kzkW',expected:'GzFg…kzkW'},vaultAuthority:{authorities:{programUpgrade:{matches:true},vaultAdmin:{matches:null},pendingAdmin:{matches:null},allocationAdmin:{matches:null}}},observedAt:'2026-10-05T10:20:00Z',sourceStatus:'kamino_api_plus_solana_rpc'});
assert.strictEqual(els['overview-position'].textContent,'Position detected');
assert.strictEqual(els['overview-authority'].textContent,'Review incomplete');
assert(/Updated /.test(els['overview-evidence'].textContent),els['overview-evidence'].textContent);
assert(els['overview-protection'].textContent.includes('Checking protection status'));
context.location.hash='#positions';
context.renderPosition({position:{name:'Steakhouse USDG High Yield',protocol:'Kamino Earn',underlyingAmount:'0.131061',totalShares:'0.122244',stakedShares:'0.122244',unstakedShares:'0',tokensPerShare:'1.072128',vault:'Vault111'},authority:{status:'active',current:'A',expected:'A',program:'Program111'},observedAt:'2026-10-05T10:20:00Z'});
assert.strictEqual(context.location.hash,'#positions');
context.renderPosition({position:null,sourceStatus:'dust_filtered',message:'No eligible positions after dust filtering'});
assert.strictEqual(context.location.hash,'#positions');
assert.strictEqual(els['position-list-status'].textContent,'No eligible positions after dust filtering');
context.location.hash='#safeguards';
context.renderPosition({position:null,sourceStatus:'indexing'});
assert.strictEqual(context.location.hash,'#safeguards');
assert.strictEqual(els['no-position'].textContent,'Position search still indexing…');
assert.strictEqual(els['position-row-amount'].textContent,'0.131061 USDG');
assert(els['position-total-shares'].textContent.includes('0.122244'));
assert(els['position-staked-shares'].textContent.includes('0.122244'));
assert(els['position-unstaked-shares'].textContent.includes('0'));
assert(els['position-vault'].textContent,'Vault111');
assert.strictEqual(els['position-program'].textContent,'Program111');
assert(!els['position-activity'].textContent.includes('verified'));
context.renderAuthority({authority:{status:'active',current:'Current',expected:'Different',program:'Program111',programData:'ProgramData111'},observedAt:'2026-10-05T10:20:00Z'});
assert.strictEqual(els['authority-badge'].textContent,'CHANGED');
assert.strictEqual(els['authority-badge'].className,'status-pill changed');
context.renderAuthority({authority:{status:'active',current:'Current',expected:null},observedAt:'2026-10-05T10:20:00Z'});
assert.equal(els['authority-badge'].textContent,'CONFIGURATION REQUIRED')
assert.strictEqual(els['authority-badge'].className,'status-pill incomplete');
assert(els['selected-safeguards'].textContent.includes('vault role baselines'));
context.renderProtection({armed:false,armedCount:0});
assert.strictEqual(els['protection-title'].textContent,'Not armed');
assert.strictEqual(els['overview-protection'].textContent,'Not armed');
assert.strictEqual(els['position-protection'].textContent,'Protection status: Not armed.');
let protectionCalls=0;context.setProtectionToken('handoff-token');context.protectionRequest=async()=>{protectionCalls++;return {armed:true,armedCount:3}};context.loadProtection().then(()=>{assert.strictEqual(protectionCalls,1);assert.strictEqual(els['overview-protection'].textContent,'Armed');assert.strictEqual(els['position-protection'].textContent,'Protection status: Armed.');context.protectionRequest=async()=>{throw new Error('unavailable')};return context.loadProtection()}).then(()=>{assert.strictEqual(els['overview-protection'].textContent,'Protection status unavailable');assert.strictEqual(els['position-protection'].textContent,'Protection status unavailable');console.log('workspace semantics runtime passed');
  sessionStore.kelvara_network_context='mainnet-beta';
  sessionStore.kelvara_app_session=JSON.stringify({wallet:'wallet',source:'phantom',token:'handoff-token',network:'mainnet-beta',genesisHash:'5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d'});
  const requestPaths=[];context.setProtectionRequest(async path=>{requestPaths.push(path);return {armed:true,armedCount:3}});context.fetch=async url=>{requestPaths.push(url);if(url==='/api/portfolio/wallet')return {ok:false,status:502,text:async()=>JSON.stringify({error:'control_plane_malformed'})};if(url==='/api/inspect/wallet')return {ok:true,status:200,text:async()=>JSON.stringify({position:null,sourceStatus:'dust_filtered',message:'No eligible positions after dust filtering'})};if(url==='/api/protection/status')return {ok:true,status:200,text:async()=>JSON.stringify({armed:true,armedCount:3})};return {ok:true,status:200,text:async()=>JSON.stringify({})}};
  return context.init().then(()=>{assert(requestPaths.includes('/api/protection/status'),`initialization must request protection independently after portfolio 502: ${requestPaths.join(',')}`);assert.strictEqual(els['protection-title'].textContent,'Armed','initialization must resolve protection status');assert(els['message'].textContent.includes('Portfolio unavailable. Retry.'),'portfolio failure must remain explicit and fail closed')});
}).catch(error=>{console.error(error);process.exitCode=1});
