const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('app.html','utf8'),source=fs.readFileSync('app.js','utf8');
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
function node(tag='div'){const classes=new Set();return {tagName:tag,classList:{add(...x){x.forEach(v=>classes.add(v))},remove(...x){x.forEach(v=>classes.delete(v))},toggle(x){if(classes.has(x))classes.delete(x);else classes.add(x)},contains(x){return classes.has(x)}},style:{setProperty(){}},dataset:{},children:[],value:'',checked:false,disabled:false,textContent:'',innerHTML:'',onclick:null,onchange:null,onkeydown:null,hidden:false,append(...x){this.children.push(...x)},appendChild(x){this.children.push(x)},addEventListener(){},setAttribute(){},replaceChildren(...x){this.children=x},closest(){return this},querySelectorAll(){return[]},getBoundingClientRect(){return {left:0,top:0,width:1,height:1}}};}
const nodes=new Map([...ids].map(id=>[id,node()]));
const rows=[]; const list=nodes.get('portfolio-positions'); list.replaceChildren=(...x)=>{rows.splice(0);rows.push(...x);list.children=rows};
const document={querySelector(s){if(s.startsWith('#'))return nodes.get(s.slice(1))||node();return node()},querySelectorAll(s){if(s==='#portfolio-positions .position-row')return rows;return[]},createElement:node,addEventListener(){}};
let calls=[]; const context={document,nodes,window:{addEventListener(){},location:{hostname:'localhost',hash:'',replace(){}}},location:{hostname:'localhost',hash:'',replace(){}},localStorage:{getItem(){return null},setItem(){},removeItem(){}},sessionStorage:{getItem(){return null},removeItem(){}},fetch:async(url)=>{calls.push(url);return {ok:true,json:async()=>({})}},setTimeout,clearTimeout,setInterval,clearInterval,Promise,URLSearchParams,Intl,DOMParser:class{},TextEncoder,atob:()=>'',btoa:()=>'',matchMedia:()=>({matches:false}),console,animalIdenticonSvg:()=>'',toast(){}};
let code=source.replace(/^import[^;]+;\n/,'').replace(/\ninit\(\);\s*$/,'');
code += `\nwalletAddress='Wallet111111111111111111111111111111111'; walletSource='phantom'; portfolioAvailable=true; activeProvider={}; evidence={position:{totalShares:'1',underlyingAmount:'1'}}; portfolioState=null; renderPortfolio({wallet:walletAddress,positions:[{targetId:'vault-a',protocol:'kamino',display:{name:'Renamed A'}},{targetId:'vault-b',protocol:'kamino',display:{name:'Renamed B'}}],safeguards:[],protocolStatuses:[],coverage:{state:'complete'}}); assert(document.querySelectorAll('#portfolio-positions .position-row').length===2); document.querySelectorAll('#portfolio-positions .position-row').forEach(row=>{row.onclick(); openEvacuation(); assert(!nodes.get('evacuation-modal').classList.contains('hidden'));});`;
vm.runInNewContext(code,{...context,assert},{filename:'app.js'});
assert.equal(calls.filter(x=>String(x).includes('/api/evacuation/prepare')).length,0);console.log('two-vault manual-exit DOM runtime passed');
