const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('app.html','utf8'), src=fs.readFileSync('app.js','utf8');
function fixture(){const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);const els={};for(const id of ids)els[id]={id,textContent:'',classList:{hidden:false,toggle(c,v){this[c]=v},add(c){this[c]=true},remove(c){this[c]=false}},setAttribute(){},onclick:null};const q=s=>s==='.position-tabs'?els.tabs: s.startsWith('#')?els[s.slice(1)]:null;els.tabs={classList:{hidden:true,add(){this.hidden=true},remove(){this.hidden=false},toggle(c,v){this.hidden=v}}};els['position-list'].querySelector=()=>els['position-list-status'];return {els,q}}
const {els,q}=fixture();const body=src.slice(src.indexOf('function setText'),src.indexOf('async function inspect'));const ctx={document:{querySelector:q,querySelectorAll:()=>[]},window:{scrollTo(){}},Intl,Date,console,$:q,format:v=>String(v),short:v=>v||'—',setInterval:()=>1,clearInterval(){},walletAddress:'wallet',walletSource:'address',evidence:null,stages:[],setStage(){},renderOverview(){},pendingTimer:null,protectionStatus:null,connectedWalletIsCurrent(){return true},toast(){},syncDiagram(){},location:{hash:''}};vm.runInNewContext(body+';this.renderPosition=renderPosition',ctx);
els['position-row'].classList.hidden=true;assert(els['position-row'].classList.hidden===true,'row fixture');
ctx.renderPosition({position:{name:'Vault Alpha',protocol:'Kamino',underlyingAmount:12.5},observedAt:'2026-01-01T00:00:00Z'});
assert(els['position-row'].classList.hidden===false);assert(els['position-card'].classList.hidden!==false);assert(els.tabs.classList.hidden!==false);
els['position-row'].onclick();assert(els['position-card'].classList.hidden===false);assert(els.tabs.classList.hidden===false);
ctx.renderPosition({sourceStatus:'dust_filtered',message:'Dust filtered'});ctx.renderPosition({sourceStatus:'indexing'});console.log('positions runtime passed');
