const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('app.html','utf8'),js=fs.readFileSync('app.js','utf8'),css=fs.readFileSync('styles.css','utf8');
for(const id of ['account-summary-grid','account-current-access','account-coverage','account-coverage-days','account-coverage-period','account-coverage-timeline','account-billing-details','account-wallet-card','account-copy-address','account-disconnect'])assert(html.includes(`id="${id}"`),`missing #${id}`);
for(const copy of ['Manage your access, billing, and wallet connection.','Current access','Standard access','Coverage','Coverage timeline','Account &amp; billing','Connected wallet'])assert(html.includes(copy),`missing ${copy}`);
for(const removed of ['account-billing','account-add-payment'])assert(!html.includes(`id="${removed}"`),`removed billing card remains: ${removed}`);
assert(js.includes('request("/api/account",true)'),'account dashboard must load authenticated persisted coverage');
assert(js.includes("coverageDaysRemaining"),'account dashboard must render server-calculated remaining days');
for(const removed of ['account-covered-positions','account-safeguard-level','account-automation','account-plan-coverage','account-service-status','Covered positions','Safeguard level','Protection automation','Service status'])assert(!html.includes(removed),`removed draft element remains: ${removed}`);
for(const asset of ['/assets/wallets/solflare.svg','/assets/wallets/phantom.svg','/assets/wallets/backpack.svg','/assets/networks/solana.svg'])assert(fs.existsSync(`.${asset}`),`missing official asset ${asset}`);
for(const fn of ['normalizeWalletProvider','renderAccountDashboard','copyAccountAddress'])assert(js.includes(`function ${fn}`),`missing ${fn}`);
assert(js.includes('navigator.clipboard.writeText(walletAddress)'),'copy must use clipboard API');
assert(!js.includes("location.hash='#protection'"),'removed protection CTA remains');
assert(js.includes("disconnectWallet"),'disconnect action missing');
assert(js.includes('post("/api/auth/logout"'),'disconnect must report authenticated session end');
assert(!html.includes('Loading authenticated session…</p><dl class="account-facts"'),'legacy account metadata screen remains');
assert(css.includes('.account-summary-grid')&&css.includes('.account-details-grid')&&css.includes('.account-timeline'),'dashboard styles missing');
assert(css.includes('@media(max-width:720px)')&&css.includes('.account-summary-grid{grid-template-columns:1fr}'),'mobile stack missing');
console.log('account dashboard contract passed');
