const assert=require('assert'),fs=require('fs'),vm=require('vm');
const index=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('app.js','utf8'),appHtml=fs.readFileSync('app.html','utf8');
const walletSource=index.match(/<script data-wallet-module>([\s\S]*?)<\/script>/)[1];
const positionsSource=index.match(/<script data-positions-module>([\s\S]*?)<\/script>/)[1];
const MAIN='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d',DEV='EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG',KEY='StaleSessionWallet111111111111111111111111111111111111';
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject}}
function clock(){let now=0,next=1,timers=new Map();return{setTimeout(fn,ms){const id=next++;timers.set(id,{at:now+ms,fn});return id},clearTimeout(id){timers.delete(id)},advance(ms){now+=ms;for(const [id,t] of [...timers])if(t.at<=now){timers.delete(id);t.fn()}},now:()=>now}}
function node(id,attrs={}){return Object.assign({id,textContent:'',value:'',hidden:false,dataset:{},listeners:{},classList:{add(){},remove(){},toggle(){}},setAttribute(n,v){this[n]=v},getAttribute(n){return this[n]},appendChild(){},replaceChildren(){},addEventListener(n,f){(this.listeners[n]??=[]).push(f)},querySelectorAll(){return[]}},attrs)}
function landing({initial='mainnet-beta',persisted=true}={}){
 const c=clock(),store=new Map(),local=new Map(),nodes=new Map();
 if(initial)store.set('kelvara_network_context',initial);
 if(persisted)store.set('kelvara_app_session',JSON.stringify({network:initial,genesisHash:initial==='devnet'?DEV:MAIN,wallet:KEY,source:'phantom',token:'t'}));
 for(const id of ['wallet-selector','wallet-selector-message','wallet-selector-status','wallet-chip','wallet-chip-address','wallet-disconnect','wallet-selector-close','network-selector','network-selector-close','network-selector-status','realm-label','asset-list','no-results','catalog-status','vault-count','vault-protocol-summary','asset-search','type-filter','protocol-filter'])nodes.set(id,node(id));
 nodes.get('wallet-selector').hidden=true;const networkButtons=['mainnet-beta','devnet'].map(network=>node('',{dataset:{network}}));nodes.get('network-selector').querySelectorAll=()=>networkButtons;
 const listeners={};const gate=deferred();let disconnects=0,connects=0,signs=0,fetches=0,catalogFetches=0;
 const provider={isConnected:true,publicKey:{toString:()=>KEY},async connect(){connects++;return{publicKey:this.publicKey}},async signMessage(){signs++;return{signature:Uint8Array.of(1)}},disconnect(){disconnects++;return gate.promise}};
 const response={ok:true,json:async()=>({network:'devnet',positions:[]})};
 const window={phantom:{solana:provider},addEventListener(n,f){(listeners[n]??=[]).push(f)},dispatchEvent(event){for(const f of listeners[event.type]||[])f(event);return true}};
 const context={window,document:{querySelector:s=>nodes.get(s.slice(1))||node(s.slice(1)),querySelectorAll:s=>s==='[data-wallet]'?[]:[],addEventListener(){}},sessionStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},localStorage:{removeItem:k=>local.delete(k),getItem:k=>local.get(k)},fetch:async url=>{fetches++;if(String(url).includes('supported-positions'))catalogFetches++;return response},CustomEvent:function(type,init){this.type=type;this.detail=init.detail},setTimeout:c.setTimeout,clearTimeout:c.clearTimeout,setInterval:c.setTimeout,clearInterval:c.clearTimeout,Date:{now:c.now},Promise,TextEncoder,btoa:s=>Buffer.from(s,'binary').toString('base64')};
 vm.runInNewContext(walletSource,context,{filename:'index.html'});vm.runInNewContext(positionsSource,context,{filename:'index.html'});
 return{context,nodes,store,provider,gate,clock:c,counts:()=>({disconnects,connects,signs,fetches,catalogFetches}),settle:()=>new Promise(r=>setImmediate(r))};
}
async function appHarness(){
 const ids=[...appHtml.matchAll(/id="([^"]+)"/g)].map(m=>m[1]),els=Object.fromEntries(ids.map(id=>[id,node(id)])),listeners={},c=clock(),session={kelvara_network_context:'mainnet-beta'},calls=[];
 const label=els['network-context-label'],selector=els['network-selector'];selector.hidden=true;selector.querySelectorAll=()=>['mainnet-beta','devnet'].map(network=>node('',{dataset:{network}}));
 let disconnects=0;const provider={isConnected:true,publicKey:{toString:()=>KEY},async disconnect(){disconnects++;throw Error('unowned provider must not disconnect')},async connect(){throw Error('must not connect')},async signMessage(){throw Error('must not sign')}};
 const doc={querySelector:s=>s.startsWith('#')?(els[s.slice(1)]||node(s.slice(1))):node(s),querySelectorAll:()=>[],createElement:()=>node('created'),addEventListener(n,f){(listeners[n]??=[]).push(f)}};
 const ctx={normalizeNetwork:v=>v==='mainnet-beta'||v==='devnet'?v:null,document:doc,window:{phantom:{solana:provider},addEventListener(){},scrollTo(){}},location:{hash:'',reload(){calls.push('reload')},replace(){}},sessionStorage:{getItem:k=>session[k]??null,setItem(k,v){session[k]=String(v)},removeItem(k){delete session[k]}},localStorage:{removeItem(){}},fetch:async()=>{calls.push('fetch');return{ok:true,text:async()=>JSON.stringify({}),json:async()=>({})}},setTimeout:c.setTimeout,clearTimeout:c.clearTimeout,setInterval:c.setTimeout,clearInterval:c.clearTimeout,Promise,URLSearchParams,Intl,DOMParser:class{},TextEncoder,atob:()=>'',btoa:()=>'',matchMedia:()=>({matches:false}),console,animalIdenticonSvg:()=>''};
 const source=app.replace(/^import[^\n]*\n/gm,'').replace(/\ninit\(\);\s*$/,'')+'\nthis.exportTests={bindNetworkControl,switchNetwork,connectWallet,inspect,authenticateProtection,armProtection,fastClose,revokeProtection,simulateEvacuation,signEvacuation};';vm.runInNewContext(source,ctx,{filename:'app.js'});return{ctx,els,selector,label,session,clock:c,calls,disconnects:()=>disconnects};
}
(async()=>{
 for(const mode of ['pending','rejected','timeout']){
  const h=landing();await h.settle();const baseline=h.counts().catalogFetches;h.nodes.get('network-selector').querySelectorAll()[1].onclick();assert.equal(h.counts().disconnects,1,mode);assert.equal(h.store.get('kelvara_network_context'),'mainnet-beta',mode+' does not persist new network while teardown incomplete');assert.equal(h.counts().catalogFetches,baseline,mode+' catalog remains idle during teardown');await h.settle();
  if(mode==='rejected')h.gate.reject(Error('disconnect failed'));else if(mode==='timeout')h.clock.advance(10001);else h.gate.resolve();await h.settle();
  if(mode==='pending'){assert.equal(h.store.get('kelvara_network_context'),'devnet');assert.equal(h.counts().catalogFetches,baseline+1,'successful teardown dispatches one new catalog load')}else{assert.equal(h.store.get('kelvara_network_context'),'mainnet-beta',mode+' keeps old network only');assert.equal(h.counts().catalogFetches,baseline,mode+' dispatches no catalog load')}}
 const stale=landing({initial:'devnet',persisted:true});await stale.settle();stale.nodes.get('network-selector').querySelectorAll()[0].onclick();assert.equal(stale.counts().disconnects,1,'stale persisted source is torn down with current null');stale.gate.resolve();await stale.settle();assert.equal(stale.store.get('kelvara_network_context'),'mainnet-beta');
 const same=landing({initial:'mainnet-beta',persisted:true});same.nodes.get('network-selector').querySelectorAll()[0].onclick();assert.equal(same.counts().disconnects,0,'same network does not disconnect');
 const ah=await appHarness();ah.session.kelvara_app_session=JSON.stringify({network:'mainnet-beta',genesisHash:MAIN,wallet:KEY,source:'phantom',token:'t'});assert.equal(ah.ctx.exportTests.switchNetwork('devnet'),true);assert.equal(ah.disconnects(),1,'app-owned provider session disconnects before switch');assert.equal(ah.session.kelvara_network_context,'mainnet-beta','failed app-owned disconnect keeps old network');ah.ctx.exportTests.bindNetworkControl();ah.label.onclick();assert.equal(ah.label['aria-expanded'],'true');ah.label.onclick();assert.equal(ah.label['aria-expanded'],'true');assert.equal(ah.calls.length,0);ah.label.onclick();ah.label.onclick();assert.equal(ah.label['aria-expanded'],'true','chooser remains runtime accessible');
 console.log('final network switch TDD regressions passed');
})().catch(e=>{console.error(e);process.exitCode=1});
function listenersOf(element,name){return element.listeners?.[name]||[]}
