const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('app.html','utf8'),source=fs.readFileSync('app.js','utf8');
assert(!/Your vault is watched in|Needs setup:/.test(html+source),'safeguards presentation has no warning-heavy summary copy');
assert(!/Baseline not configured|setup-incomplete|Setup incomplete/.test(html+source),'customer-facing incomplete copy avoids deprecated setup wording');
assert(/Configuration required|configuration required/.test(html+source),'customer-facing incomplete copy uses Configuration required');
assert(html.includes('<details class="safeguard-explanation">'),'authority explanation is a disclosure');
assert(html.includes('<summary>Why this matters</summary>'),'authority disclosure has a compact summary');
assert(html.includes('The program owner can replace the deployed Kamino kVault code. If the owner changes, it is a high-signal security event, but not proof of malicious activity.'),'authority explanation remains exact');
assert(!/legend|status legend|green.*yellow.*red/i.test(html+source),'no status legend is added');
function el(tag='div'){return {tagName:tag.toUpperCase(),children:[],dataset:{},textContent:'',innerHTML:'',className:'',hidden:false,disabled:false,attributes:{},classList:{hidden:false,add(c){this[c]=true},remove(c){this[c]=false},toggle(c,v){this[c]=v===undefined?!this[c]:v}},setAttribute(k,v){this.attributes[k]=v},appendChild(x){this.children.push(x);return x},append(...x){this.children.push(...x)},replaceChildren(...x){this.children=x},addEventListener(){}}}
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
const els=Object.fromEntries([...new Set(ids)].map(id=>[id,el()]));els['position-tabs']=el();
const document={createElement:tag=>el(tag),querySelector(s){if(s==='.position-tabs')return els['position-tabs'];return s[0]==='#'?els[s.slice(1)]:null},querySelectorAll(s){if(s.includes('.position-row'))return els['portfolio-positions'].children;return []}};
const ctx={document,$:s=>document.querySelector(s),setText:(s,v)=>{const x=document.querySelector(s);if(x)x.textContent=String(v)},renderOverview(){},format:v=>String(v),authorityAssessment(data){const a=data?.authority||{};if(a.current&&a.expected)return a.current===a.expected?{state:'matches',label:'Matches configured baseline'}:{state:'changed',label:'Changed'};if(a.current||a.expected)return{state:'incomplete',label:'Configuration required'};return{state:'pending',label:'Checking safeguards…'}},vaultRoleCoverage(data){const authorities=data?.vaultAuthority?.authorities||{};const roles=['vaultAdmin','pendingAdmin','allocationAdmin'];return{missing:roles.filter(role=>authorities[role]?.matches==null),total:roles.length}},observedCopy(){return 'Observed'},positionSearchPending(){return false},positionEmptyCopy(){return 'empty'},clearInterval(){},setInterval(){return 1},pendingTimer:null,protectionStatus:null,renderPosition(){},projectWalletSafeguards:p=>p.positions.flatMap(x=>x.safeguards||[]),console};
const start=source.indexOf('function renderPortfolio');
const end=source.indexOf('async function inspect');
vm.runInNewContext(source.slice(start,end)+';this.renderPortfolio=renderPortfolio;this.renderAuthority=renderAuthority',ctx);
const portfolio={positions:[{targetId:'a',protocol:'Kamino',display:{name:'Vault A'},safeguards:[{targetId:'a',ruleId:'r1',result:'pass',receiptId:'receipt'}]},{targetId:'b',protocol:'Generic',display:{name:'Vault B'},safeguards:[]}],safeguards:[{targetId:'a',ruleId:'r1',result:'pass',receiptId:'receipt'}],protocolStatuses:[],coverage:{state:'partial'}};
ctx.portfolioState=portfolio;ctx.renderPortfolio(portfolio);
assert.strictEqual(els['safeguards-summary'].textContent,'Safeguard evidence','portfolio render keeps concise safeguards heading');
assert.strictEqual(els['portfolio-coverage'].textContent,'Coverage partial: unknown/unknown satisfied','portfolio keeps detailed coverage row');
ctx.renderAuthority({authority:{current:'current',expected:'expected'},vaultAuthority:{authorities:{vaultAdmin:{matches:true}}}});
assert.strictEqual(els['safeguards-summary'].textContent,'Safeguard evidence','authority render keeps concise safeguards heading');
assert.match(els['vault-roles-status'].textContent,/Configuration required/,'authority keeps professional detailed configuration status');
assert.doesNotMatch(els['safeguards-summary'].textContent,/connected vault|baseline|review incomplete|changed/i,'summary avoids count and warning coverage prose');
console.log('safeguards presentation runtime passed: portfolio and authority render paths exercised');
