const assert = require('assert');
const fs = require('fs');
const landing = fs.readFileSync('index.deployed.html','utf8');
const app = fs.readFileSync('app.html','utf8');
const appJs = fs.readFileSync('app.js','utf8');
const css = landing.match(/<style>([\s\S]*?)<\/style>/)[1];
assert.match(css, /\.scope::before[\s\S]*radial-gradient\(circle/);
assert.doesNotMatch(landing, /<link[^>]+styles\.css/);
assert.match(app, /id="pane-positions"/);
assert.match(app, /<link rel="stylesheet" href="\/styles\.css/);
assert.match(app, /<script[^>]+src="\/app\.js\?v=network-switch-1"/);
assert.doesNotMatch(app, /stage-boot|SECURE SESSION|Verifying/);
assert.match(landing, /sessionStorage\.setItem\(['"]kelvara_handoff['"]/);
assert.doesNotMatch(landing, /localStorage/);
assert.match(landing, /location\.replace\(['"]\/app\.html/);
assert.match(appJs, /sessionStorage\.getItem\(['"]kelvara_handoff['"]\)/);
assert.match(appJs, /sessionStorage\.removeItem\(['"]kelvara_handoff['"]\)/);
assert.match(appJs, /current!==handoff\.wallet/);
assert.match(appJs, /restoreAppSession/);
assert.match(appJs, /kelvara_app_session/);
assert.doesNotMatch(appJs, /localStorage\.setItem\(["']kelvara_prod_wallet/);
for (const [kind, asset] of [['phantom','phantom.svg'],['solflare','solflare.svg'],['backpack','backpack.svg']]) assert.match(landing, new RegExp(`data-wallet="${kind}"[\\s\\S]*?assets/wallets/${asset}`));
assert.match(landing, /p\.isConnected===false/);
console.log('wallet handoff tests passed: session-only landing/app contract');
