import assert from 'node:assert';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync('index.html','utf8');
const start=html.indexOf('<script data-wallet-module>'),end=html.indexOf('</script>',start)+9;
const module=html.slice(start,end).replace(/^<script[^>]*>|<\/script>$/g,'');
const MAIN='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d', DEV='EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG', key='11111111111111111111111111111111';
const stale={kelvara_handoff:'stale-handoff',kelvara_app_session:'stale-session',kelvara_auth_token:'stale-token',kelvara_prod_monitor_wallet:'stale-wallet'};
function store(seed={}){const data=new Map(Object.entries(seed));return{data,getItem:k=>data.has(k)?data.get(k):null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)}}
function el(){return{hidden:false,textContent:'',onclick:null,querySelectorAll:s=>s==='[data-network]'?[{dataset:{network:'mainnet-beta'},onclick:null},{dataset:{network:'devnet'},onclick:null}]:s==='[data-wallet]'?[{dataset:{wallet:'phantom'},onclick:null}]:[]}}
function response(spec){return{ok:spec.status===undefined||spec.status>=200&&spec.status<300,json:async()=>{if(spec.jsonError)throw Error('bad json');return spec.body}}}
async function run({network,challenge={message:'challenge',network:'mainnet-beta',genesisHash:MAIN},session={token:'token',network:'mainnet-beta',genesisHash:MAIN},challengeStatus=200,verifyStatus=200,inspectStatus=200,challengeJsonError=false,verifyJsonError=false,inspectJsonError=false,inspectBody={position:{}},seed=true}={}){
 const seedData=seed?{...stale,kelvara_network_context:network}:{};const sessionStorage=store(seedData),localStorage=store(seed?{kelvara_prod_monitor_wallet:'stale-wallet'}:{}),walletButton={dataset:{wallet:'phantom'},onclick:null},nodes=new Map(['wallet-selector','network-selector','network-selector-status','wallet-selector-message','wallet-chip','wallet-chip-address','wallet-disconnect','wallet-selector-close','realm-label'].map(id=>[id,el()]));
 nodes.get('wallet-selector').querySelectorAll=()=>[walletButton];nodes.get('network-selector').querySelectorAll=()=>[];const calls=[];let signs=0,redirect;
 const provider={isConnected:true,publicKey:{toString:()=>key},connect:async()=>({publicKey:provider.publicKey}),signMessage:async()=>{signs++;return{signature:new Uint8Array([1,2,3])}},on(){},disconnect:async()=>{}};
 const context={window:{phantom:{solana:provider}},sessionStorage,localStorage,location:{replace:u=>redirect=u},document:{querySelector:s=>nodes.get(s.slice(1))||{querySelectorAll:()=>[],addEventListener(){}},querySelectorAll:s=>s==='[data-wallet]'?[walletButton]:[],addEventListener(){}},fetch:async(url,opts)=>{calls.push([url,opts]);if(url.endsWith('/challenge'))return response({status:challengeStatus,body:challenge,jsonError:challengeJsonError});if(url.endsWith('/verify'))return response({status:verifyStatus,body:session,jsonError:verifyJsonError});if(url.includes('/inspect/'))return response({status:inspectStatus,body:inspectBody,jsonError:inspectJsonError});throw Error('unexpected fetch')},TextEncoder,btoa:s=>Buffer.from(s,'binary').toString('base64'),console};
 vm.runInNewContext(module,context);await walletButton.onclick();await new Promise(r=>setImmediate(r));return{calls,signs,redirect,sessionStorage,localStorage};
}
function assertCleared(r){for(const k of Object.keys(stale)){const storage=k==='kelvara_prod_monitor_wallet'?r.localStorage:r.sessionStorage;assert.strictEqual(storage.getItem(k),null,k)}}
(async()=>{
 let r=await run({network:'mainnet-beta'});assert.strictEqual(r.signs,1);assert.strictEqual(r.calls.length,3);assert.deepStrictEqual(JSON.parse(r.calls[0][1].body),{wallet:key,network:'mainnet-beta'});assert.deepStrictEqual(JSON.parse(r.calls[1][1].body),{wallet:key,message:'challenge',signature:'AQID',network:'mainnet-beta'});assert.strictEqual(r.calls[2][1].headers.authorization,'Bearer token');assert.strictEqual(r.calls[2][1].headers['x-kelvara-network'],'mainnet-beta');assert.strictEqual(r.calls[2][1].headers['x-kelvara-genesis'],MAIN);assert.strictEqual(r.redirect,'/app.html');assert.deepStrictEqual(JSON.parse(r.sessionStorage.getItem('kelvara_handoff')),{wallet:key,source:'phantom',token:'token',network:'mainnet-beta',genesisHash:MAIN,evidence:{position:{}}});
 for(const spec of [{challengeStatus:500},{challengeJsonError:true},{challenge:null},{challenge:{message:'challenge',network:'devnet',genesisHash:MAIN}},{challenge:{message:'challenge',network:'mainnet-beta'}}]){r=await run({network:'mainnet-beta',...spec});assert.strictEqual(r.signs,0);assert.strictEqual(r.calls.length,1);assert.strictEqual(r.redirect,undefined);assertCleared(r)}
 for(const spec of [{verifyStatus:500},{verifyJsonError:true},{session:null},{session:{token:'token',network:'devnet',genesisHash:MAIN}},{session:{token:'token',network:'mainnet-beta'}},{session:{token:'token',network:'mainnet-beta',genesisHash:'wrong'}}]){r=await run({network:'mainnet-beta',...spec});assert.strictEqual(r.signs,1);assert.strictEqual(r.calls.length,2);assert.strictEqual(r.redirect,undefined);assertCleared(r)}
 for(const spec of [{inspectStatus:500},{inspectJsonError:true},{inspectBody:null}]){r=await run({network:'mainnet-beta',...spec});assert.strictEqual(r.signs,1);assert.strictEqual(r.calls.length,3);assert.strictEqual(r.redirect,undefined);assertCleared(r)}
 for(const network of ['devnet',undefined,'bogus']){r=await run({network});assert.strictEqual(r.signs,0);assert.strictEqual(r.calls.length,0);assert.strictEqual(r.redirect,undefined);assertCleared(r)}
 console.log('root auth dynamic failure matrix passed');
})().catch(error=>{console.error(error);process.exitCode=1});
